{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ include "k8s-export.namespace" . }}
  labels:
    {{- include "k8s-export.appLabels" (dict "name" .Values.postgres.name "root" . "component" "database") | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: postgres
{{- end }}