apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: axric-api
  namespace: axric
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: axric-api
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: axric-fe
  name: axric-fe
  namespace: axric
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: axric-fe
  sessionAffinity: None
  type: ClusterIP
---

