{{- $ing := (default dict .Values.ingress) }}
{{- $axricIng := (default dict .Values.apps.axricIngress) }}
{{- if (default false $axricIng.enabled) }}
{{- $ing = $axricIng }}
{{- end }}
{{- if (default false $ing.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ing.name | default (printf "%s-ingress" (include "k8s-export.name" .)) }}
  namespace: {{ include "k8s-export.namespace" . }}
  labels:
    {{- include "k8s-export.labels" . | nindent 4 }}
  {{- $annotations := merge (dict "nginx.ingress.kubernetes.io/force-ssl-redirect" "true") (default dict $ing.annotations) }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
spec:
  {{- if $ing.className }}
  ingressClassName: {{ $ing.className }}
  {{- end }}
  rules:
    {{- range $ing.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
  {{- with $ing.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

