apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"application-controller","app.kubernetes.io/name":"argocd-application-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-application-controller","namespace":"argocd"}}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/component: application-controller
      app.kubernetes.io/name: argocd-application-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-application-controller
    namespace: argocd
    resourceVersion: "878"
    uid: c6ad1c56-53f9-4943-9a6b-3ebdb7e2686f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"applicationset-controller","app.kubernetes.io/name":"argocd-applicationset-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-applicationset-controller","namespace":"argocd"}}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/component: applicationset-controller
      app.kubernetes.io/name: argocd-applicationset-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-applicationset-controller
    namespace: argocd
    resourceVersion: "879"
    uid: ef35ddfe-7c16-4ebd-9734-af51ad981cf9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"dex-server","app.kubernetes.io/name":"argocd-dex-server","app.kubernetes.io/part-of":"argocd"},"name":"argocd-dex-server","namespace":"argocd"}}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/part-of: argocd
    name: argocd-dex-server
    namespace: argocd
    resourceVersion: "881"
    uid: 8509552c-0e6c-4664-8d1d-febf5404e06e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-controller","namespace":"argocd"}}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-controller
    namespace: argocd
    resourceVersion: "882"
    uid: 8088a1b1-8a76-4e8a-9bff-978da306edda
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"redis","app.kubernetes.io/name":"argocd-redis","app.kubernetes.io/part-of":"argocd"},"name":"argocd-redis","namespace":"argocd"}}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: argocd-redis
      app.kubernetes.io/part-of: argocd
    name: argocd-redis
    namespace: argocd
    resourceVersion: "884"
    uid: 0d77cb94-7d35-48fc-8990-82db9720e5a2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"repo-server","app.kubernetes.io/name":"argocd-repo-server","app.kubernetes.io/part-of":"argocd"},"name":"argocd-repo-server","namespace":"argocd"}}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/component: repo-server
      app.kubernetes.io/name: argocd-repo-server
      app.kubernetes.io/part-of: argocd
    name: argocd-repo-server
    namespace: argocd
    resourceVersion: "885"
    uid: 0bf49fad-b770-436b-b1b1-14fe1792e2f2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/name":"argocd-server","app.kubernetes.io/part-of":"argocd"},"name":"argocd-server","namespace":"argocd"}}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
    name: argocd-server
    namespace: argocd
    resourceVersion: "886"
    uid: 66e034be-b1da-4a51-b6f7-45bd18fdb8eb
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T08:01:21Z"
    name: default
    namespace: argocd
    resourceVersion: "852"
    uid: c13a61c3-a158-43aa-96b9-2752526d5b1c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T09:18:10Z"
    name: default
    namespace: axric
    resourceVersion: "9048"
    uid: f93360b1-4f7e-4290-b8a6-0c2840b4ad95
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: postgres
      meta.helm.sh/release-namespace: axric
    creationTimestamp: "2026-03-10T02:50:05Z"
    labels:
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 18.3.0
      helm.sh/chart: postgresql-18.5.5
    name: postgres-postgresql
    namespace: axric
    resourceVersion: "723608"
    uid: e236f027-e465-4b6f-8d39-f9f9cb977fc0
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-04-17T12:58:55Z"
    name: default
    namespace: database
    resourceVersion: "5567195"
    uid: 4bd0390f-e144-45c2-acaa-53763a407f6f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:56Z"
    name: default
    namespace: default
    resourceVersion: "375"
    uid: ea74cddc-18c1-4549-93bb-c08878637438
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-05T04:16:49Z"
    name: default
    namespace: ingress-nginx
    resourceVersion: "99076"
    uid: 73fbb9f1-5f18-4848-9469-a7345dd911f8
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.14.3"},"name":"ingress-nginx","namespace":"ingress-nginx"}}
    creationTimestamp: "2026-03-05T04:16:49Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.14.3
    name: ingress-nginx
    namespace: ingress-nginx
    resourceVersion: "99074"
    uid: bdac9311-0494-4f72-9ad3-4ea756faa2eb
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"admission-webhook","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.14.3"},"name":"ingress-nginx-admission","namespace":"ingress-nginx"}}
    creationTimestamp: "2026-03-05T04:16:49Z"
    labels:
      app.kubernetes.io/component: admission-webhook
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.14.3
    name: ingress-nginx-admission
    namespace: ingress-nginx
    resourceVersion: "99077"
    uid: b6b43206-9738-4286-ad3a-667a389f5b0a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:56Z"
    name: default
    namespace: kube-node-lease
    resourceVersion: "377"
    uid: e59ed9fd-c2af-4101-9f2a-457ff911f6da
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:56Z"
    name: default
    namespace: kube-public
    resourceVersion: "380"
    uid: aa24e6d9-cfd3-45cf-9c87-5dc5eb16bdb8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:43Z"
    name: attachdetach-controller
    namespace: kube-system
    resourceVersion: "271"
    uid: 24d41b5b-dcfe-45d6-99ae-9272a9608b2d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: bootstrap-signer
    namespace: kube-system
    resourceVersion: "252"
    uid: e93cca39-1023-4634-992e-e5514abefb67
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"calico-cni-plugin","namespace":"kube-system"}}
    creationTimestamp: "2026-03-04T07:59:46Z"
    name: calico-cni-plugin
    namespace: kube-system
    resourceVersion: "485"
    uid: 2e15a6b2-4349-4b66-9120-dba3e6b7289b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"calico-kube-controllers","namespace":"kube-system"}}
    creationTimestamp: "2026-03-04T07:59:46Z"
    name: calico-kube-controllers
    namespace: kube-system
    resourceVersion: "480"
    uid: 7372f7c4-1c31-405b-bd5b-da96bc144273
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"calico-node","namespace":"kube-system"}}
    creationTimestamp: "2026-03-04T07:59:46Z"
    name: calico-node
    namespace: kube-system
    resourceVersion: "484"
    uid: 5e4160a6-ef42-448b-b5a4-4ecab8f371a9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: certificate-controller
    namespace: kube-system
    resourceVersion: "257"
    uid: 4dc8affe-3627-4984-b60b-44664b84ea9d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: clusterrole-aggregation-controller
    namespace: kube-system
    resourceVersion: "346"
    uid: 79ddf90d-ce09-4f48-9f0d-ceb0a484425f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:44Z"
    name: coredns
    namespace: kube-system
    resourceVersion: "282"
    uid: a51fdd03-45df-449a-8b3d-989d5f96d165
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:43Z"
    name: cronjob-controller
    namespace: kube-system
    resourceVersion: "270"
    uid: 6977b0dd-07e4-4f69-9bc3-a8d728d61198
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: daemon-set-controller
    namespace: kube-system
    resourceVersion: "334"
    uid: 3780ab6d-2034-457b-85b8-133a9d9fac21
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:56Z"
    name: default
    namespace: kube-system
    resourceVersion: "382"
    uid: 97037c2c-062d-40e2-93fa-5f1890292776
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: deployment-controller
    namespace: kube-system
    resourceVersion: "250"
    uid: 031064a4-86a2-49b7-8433-d98ac0c64f79
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: disruption-controller
    namespace: kube-system
    resourceVersion: "339"
    uid: 8623f404-73e4-42eb-a8b9-05611f8c1b45
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: endpoint-controller
    namespace: kube-system
    resourceVersion: "329"
    uid: 1e1d1e2f-6d03-4bd0-bb6a-ff9f51086eff
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: endpointslice-controller
    namespace: kube-system
    resourceVersion: "247"
    uid: d027d9ec-3ce2-47bd-8a42-eac5e5318b96
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: endpointslicemirroring-controller
    namespace: kube-system
    resourceVersion: "256"
    uid: 511d87cc-7d56-4aeb-a66e-e894ff346c72
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:55Z"
    name: ephemeral-volume-controller
    namespace: kube-system
    resourceVersion: "348"
    uid: 62519ed5-054d-4b27-9eb3-f70ae53ca8ce
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: expand-controller
    namespace: kube-system
    resourceVersion: "253"
    uid: 5a3d4d31-7a05-4d83-aea2-1bcb64b13693
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: generic-garbage-collector
    namespace: kube-system
    resourceVersion: "333"
    uid: 0ee72c46-224a-4679-b468-2b5050145caf
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: horizontal-pod-autoscaler
    namespace: kube-system
    resourceVersion: "259"
    uid: 432d706e-45b8-4d3e-9df4-1d266c35cbfe
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: job-controller
    namespace: kube-system
    resourceVersion: "338"
    uid: f0ae80df-0b42-4672-9f25-f562a547fa96
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:44Z"
    name: kube-proxy
    namespace: kube-system
    resourceVersion: "289"
    uid: cc0a704f-ddf5-498b-b4cc-7cdcf43aaea4
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: legacy-service-account-token-cleaner
    namespace: kube-system
    resourceVersion: "345"
    uid: 829cce51-7369-44fa-9db8-8e2bcb1a6a57
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:43Z"
    name: namespace-controller
    namespace: kube-system
    resourceVersion: "272"
    uid: 2e573333-241d-4d51-98aa-10f7d49587eb
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: node-controller
    namespace: kube-system
    resourceVersion: "254"
    uid: e257c9bf-c956-4dfa-b6b1-8ab412767485
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: persistent-volume-binder
    namespace: kube-system
    resourceVersion: "341"
    uid: 850f27b5-a547-4638-8a56-fb19f50e136e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: pod-garbage-collector
    namespace: kube-system
    resourceVersion: "249"
    uid: b7f46bfa-edd3-464c-acf8-25ecde9c8577
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:43Z"
    name: pv-protection-controller
    namespace: kube-system
    resourceVersion: "275"
    uid: 08feb02b-9206-4984-9c50-8b504e945145
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: pvc-protection-controller
    namespace: kube-system
    resourceVersion: "245"
    uid: dcd98a16-121a-42c1-a5d4-939332bf08d8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:43Z"
    name: replicaset-controller
    namespace: kube-system
    resourceVersion: "273"
    uid: f2f05cf8-5690-4b9a-9a53-d5994cb5c1f9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: replication-controller
    namespace: kube-system
    resourceVersion: "248"
    uid: f9450aef-97e9-496a-9027-bc66e34e6769
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: resourcequota-controller
    namespace: kube-system
    resourceVersion: "331"
    uid: cac3e51d-999a-4302-8cba-de64aaff49b3
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: root-ca-cert-publisher
    namespace: kube-system
    resourceVersion: "336"
    uid: ab1bde65-c4ca-4c6c-ad5b-bc160bdad84d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: service-account-controller
    namespace: kube-system
    resourceVersion: "332"
    uid: e20fbd3a-0e36-4b2a-8e8a-8885e91edc40
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: service-controller
    namespace: kube-system
    resourceVersion: "255"
    uid: 3ce3bac4-9ea8-4e6d-80a9-f3cd74ac8055
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:42Z"
    name: statefulset-controller
    namespace: kube-system
    resourceVersion: "251"
    uid: 906fe053-a72d-4503-95e7-34db11265ddb
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:54Z"
    name: token-cleaner
    namespace: kube-system
    resourceVersion: "335"
    uid: a2154b57-3efe-4626-968c-6b201533613d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:55Z"
    name: ttl-after-finished-controller
    namespace: kube-system
    resourceVersion: "347"
    uid: d867920d-2afc-46b6-b2d8-73b732a7810e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-04T07:58:43Z"
    name: ttl-controller
    namespace: kube-system
    resourceVersion: "274"
    uid: e2bd60f0-ff79-4201-b88c-9e981e089ac5
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-10T02:53:59Z"
    name: default
    namespace: local-path-storage
    resourceVersion: "723993"
    uid: 6704252c-e1d3-42be-af5e-576c3e8bfb5a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"local-path-provisioner-service-account","namespace":"local-path-storage"}}
    creationTimestamp: "2026-03-10T02:53:59Z"
    name: local-path-provisioner-service-account
    namespace: local-path-storage
    resourceVersion: "723990"
    uid: cbb0a7d3-a9c4-41c0-9c16-cea234048f2f
kind: List
metadata:
  resourceVersion: ""
