apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: ClusterInformation
  metadata:
    annotations:
      projectcalico.org/metadata: '{"uid":"9cab006b-d783-4d2a-8dfc-faf77434ae22","creationTimestamp":"2026-03-04T08:00:37Z"}'
    creationTimestamp: "2026-03-04T08:00:37Z"
    generation: 1
    name: default
    resourceVersion: "748"
    uid: 84f03b94-171d-4cdc-92dc-a0c32bc8fb8a
  spec:
    calicoVersion: v3.27.2
    clusterGUID: 4654c7370a224ddcaf14e9d231e1a93b
    clusterType: k8s,bgp,kubeadm,kdd
    datastoreReady: true
kind: List
metadata:
  resourceVersion: ""
