apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    creationTimestamp: "2026-03-04T10:41:17Z"
    generation: 4
    name: axric
    namespace: argocd
    resourceVersion: "14672"
    uid: 0ef3a600-9f02-4c29-81c0-4633198c5d79
  spec:
    clusterResourceBlacklist:
    - group: '*'
      kind: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    namespaceResourceBlacklist:
    - group: '*'
      kind: '*'
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceRepos:
    - '*'
  status: {}
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    creationTimestamp: "2026-03-04T08:02:26Z"
    generation: 1
    name: default
    namespace: argocd
    resourceVersion: "1202"
    uid: 7b2f1d6f-7090-4923-9f4d-088f8157d567
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: '*'
      server: '*'
    sourceRepos:
    - '*'
  status: {}
kind: List
metadata:
  resourceVersion: ""
