apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: axric-release
    meta.helm.sh/release-namespace: axric
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default
  namespace: axric
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: my-nginx
    meta.helm.sh/release-namespace: axric
  labels:
    app.kubernetes.io/instance: my-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.31.1
    helm.sh/chart: nginx-25.0.5
  name: my-nginx
  namespace: axric
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: axric-release
    meta.helm.sh/release-namespace: axric
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 18.3.0
    helm.sh/chart: postgresql-18.5.5
  name: postgres-postgresql
  namespace: axric
---

