{{- if .Values.serviceAccounts.create }}
{{- range .Values.serviceAccounts.items }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ include "k8s-export.namespace" $ }}
  labels:
    {{- include "k8s-export.labels" $ | nindent 4 }}
automountServiceAccountToken: {{ .automountServiceAccountToken | default false }}
{{- end }}
{{- end }}

