apiVersion: v1
kind: Service
metadata:
  name: axric-fe
  namespace: axric
  labels:
    app: axric-fe
spec:
  type: NodePort
  selector:
    app: axric-fe
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30432
      protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4