{{- if and .Values.apps.rekakimBackend.enabled .Values.apps.rekakimBackend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.apps.rekakimBackend.name }}
  namespace: {{ .Values.apps.rekakimBackend.namespace }}
  labels:
    app: {{ .Values.apps.rekakimBackend.name }}
  {{- with .Values.apps.rekakimBackend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.apps.rekakimBackend.ingress.host }}
    http:
      paths:
      - path: {{ .Values.apps.rekakimBackend.ingress.path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.apps.rekakimBackend.name }}
            port:
              number: {{ .Values.apps.rekakimBackend.service.port }}
  {{- if .Values.apps.rekakimBackend.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.apps.rekakimBackend.ingress.host }}
    secretName: {{ .Values.apps.rekakimBackend.ingress.tlsSecret }}
  {{- end }}
{{- end }}

