apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    annotations:
      projectcalico.org/metadata: '{"uid":"fcc2c85f-8011-4c04-9e71-7da6d67fc2f8","creationTimestamp":"2026-03-04T08:00:37Z"}'
    creationTimestamp: "2026-03-04T08:00:37Z"
    generation: 1
    name: default-ipv4-ippool
    resourceVersion: "747"
    uid: 94db6f48-80b8-4dc4-90f5-c038ba31615f
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 192.168.0.0/16
    ipipMode: Always
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: List
metadata:
  resourceVersion: ""
