{{- if .Values.apps.rekakimBackend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apps.rekakimBackend.name }}
  namespace: {{ .Values.apps.rekakimBackend.namespace }}
  labels:
    app: {{ .Values.apps.rekakimBackend.name }}
{{- end }}

