{{- if .Values.apps.threadlyBackend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apps.threadlyBackend.name }}
  namespace: {{ .Values.namespace.default }}
  labels:
    app: {{ .Values.apps.threadlyBackend.name }}
{{- end }}
