apiVersion: v1
items:
- apiVersion: v1
  data:
    password: MFlLRllmaXFYWC10eThpTw==
  kind: Secret
  metadata:
    creationTimestamp: "2026-03-04T08:02:26Z"
    name: argocd-initial-admin-secret
    namespace: argocd
    resourceVersion: "1196"
    uid: aa87fae7-c24e-403f-a9a5-c72ecb0378ab
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-secret
    namespace: argocd
    resourceVersion: "912"
    uid: 7ce0087f-1289-4c14-8d38-7a165ce2c23d
  type: Opaque
- apiVersion: v1
  data:
    auth: MzdpTWxQM3hZdGFUWVV3UA==
  kind: Secret
  metadata:
    creationTimestamp: "2026-03-04T08:02:22Z"
    name: argocd-redis
    namespace: argocd
    resourceVersion: "1158"
    uid: 9e73d2c1-ceb3-494d-b3fe-2c7335cfe701
  type: Opaque
- apiVersion: v1
  data:
    admin.password: JDJhJDEwJEpyOHdWUjNuR2tpZVBhZVRJaW1IRGV5MXlxRnRFQXk1VUpqTFAzTU5aZlVScmo1b25rS0Q2
    admin.passwordMtime: MjAyNi0wMy0wNFQwODowMjoyNVo=
    server.secretkey: c0Q1cEphdHp1MXBwdzhpSHhqSWtnUnRveTNRMHV3YjRBakJBaWlvREsvOD0=
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZekNDQWt1Z0F3SUJBZ0lSQUpXWlhYM1RHWU1XTklSbW1FdG5nSlF3RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRBZUZ3MHlOakF6TURRd09EQXlNalphRncweU56QXpNRFF3T0RBeQpNalphTUJJeEVEQU9CZ05WQkFvVEIwRnlaMjhnUTBRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDL0VGN1dQc0h3QmdqUHA1V3JsN1B5STAveDJtc1JrMy9aM2VJU2ZLbHp6MysvcHQzaGNMelEKUFJrYzg0eEpMVGxOYi9hMnFjL0c3VHpKU0s3bXEySEdvUU5oMFp4R1U1b05sKy82b0ZXbEJDcGduSmZVT2hYMApmWFBHSnNHZTVZMHdmMnJzZU94ci9oOFEvU05Za1dNYkI1ZlduZDJSOS9RQ1Y4RklodUpTanFNYlNnUkhVaEF2CjVLbldGdmoxR2c4KytiMHBWWFdFZW1LUVNWdi9HZGtBK1hhOHRQcnp5NXZ3ajdvaUFJcmZ1Z0tsaFZIWjJCeFgKY0tNRWJ5YldESHZPbWpuYnYzb2FHUVY0YzRGMVRoVHpoci9Nb1VXVUlmVkNveVNtNEV3cVY5ODVCdHFJOWZPcgp2ekp1ZEFkZTBQdHFHcUF1YlpmQlFFYnByRWd4RnVZZkFnTUJBQUdqZ2JNd2diQXdEZ1lEVlIwUEFRSC9CQVFECkFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdld1lEVlIwUkJIUXcKY29JSmJHOWpZV3hvYjNOMGdnMWhjbWR2WTJRdGMyVnlkbVZ5Z2hSaGNtZHZZMlF0YzJWeWRtVnlMbUZ5WjI5agpaSUlZWVhKbmIyTmtMWE5sY25abGNpNWhjbWR2WTJRdWMzWmpnaVpoY21kdlkyUXRjMlZ5ZG1WeUxtRnlaMjlqClpDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFOZ2lsZXBYbDR3TnAKSFI0YURuWlNBMGtMaldOalk5VjF4eVpDd0xzdXhGd1p0bjBaRHhKMUFLMGNqQUxzMGdRZEk5SEZSK2NFam5WNwpac0ZKeDNkSTV5dG1wbitRRC8wdEpyRnRCSHJWSlZBdlVJN3hGU3QydGJ6TlcxNTFUWVE4YUtqWU5nT0J3SmZWCm9xVFlaRElBZ04ycWtucFZkZ3Qyc3lqb3dBZC9MUkVIUGZSQmtRSmt1MTNpK2E0OG1GQ2c0eDFBMXY1d1pFSXkKckRhanprRnhWQUtZRlpWT3puT2xSL2FsVTFPR0ZJdC9UWVlzcTYvZWZ5RS9QRnNFSmpjNUxEMFRhVnY3aEU1cwpGYWw2OEVESjQvZm1QYTlFc0dUOHBrQ3JJa0FlR05JeTEvMW5GRlQxbkpPUDAyd0MxY3BGclloNU5YM3JLY0tECjJTU3VlMWlRc0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdnhCZTFqN0I4QVlJejZlVnE1ZXo4aU5QOGRwckVaTi8yZDNpRW55cGM4OS92NmJkCjRYQzgwRDBaSFBPTVNTMDVUVy8ydHFuUHh1MDh5VWl1NXF0aHhxRURZZEdjUmxPYURaZnYrcUJWcFFRcVlKeVgKMURvVjlIMXp4aWJCbnVXTk1IOXE3SGpzYS80ZkVQMGpXSkZqR3dlWDFwM2RrZmYwQWxmQlNJYmlVbzZqRzBvRQpSMUlRTCtTcDFoYjQ5Um9QUHZtOUtWVjFoSHBpa0VsYi94blpBUGwydkxUNjg4dWI4SSs2SWdDSzM3b0NwWVZSCjJkZ2NWM0NqQkc4bTFneDd6cG81Mjc5Nkdoa0ZlSE9CZFU0VTg0YS96S0ZGbENIMVFxTWtwdUJNS2xmZk9RYmEKaVBYenE3OHliblFIWHREN2FocWdMbTJYd1VCRzZheElNUmJtSHdJREFRQUJBb0lCQUJnVHRWL0U3aVkrY2NNago3ZUIvR3RZRjk5VVZIb09nZ0JsY1gxalB0NEE0bUhOTHBvK2s1L3Vnak1HYjVLOGVzU2MrVjJ0b0NzbVpWbkpSCnVTTlRCWWRFL2NBZDdLdVFHQ0c1RVN6QmQ3UWhINVg5SmNUcmJQT0ZFUFNFMHh3Z1MvZmQ3QU43V1krM3FRS04KdVI2TmM3Sm05VGkrWnJyZzhZYmt1QjZ1UzJiMllCRlBycjlsZ0RMaHRCSWJsSTJJMjlsSkdIaGlndy96ZWlIUwpkK3NMT211UjNMVzY1T2pZTTgvd3dKcGFtNi9XTFhUbWQwcExyckJhck5Bc3RlT1pobTliVlRVS3BFTldvcm5WCk15a2JRWTZsKzlqdHJoaytPY2dna1NOd3h6Zi9iV3pneVZod2YwL0pCZUdLeThFYnVVVUxkeEh4c1ZVeUNBNlcKOVdpL3Y0RUNnWUVBNm82MXdXNzh2dDZLbUlzMldvSS96Qy9SSWxQQkl6WUJOeEFGSWN3Z0pBK1pUOFhDZUNMTQpubmJJYkZaY2hMcEZUYUUxMlpMRWgyK3lVM1dMMSswZExxVlhjdzlkb3dIaHpoV29mWEsrMkhuR1o2OTlCMFQ4CjVHd1liTVpIYnNsSDBVMkZjaWFQelpvaEVSYjJBY0tITXpDQUtKQnJPaTJESW5jeHdBUERnSGtDZ1lFQTBJZksKNWVGZ2ZVZ0k3V0hlTGo1Y1U3Q3dodk1wZi9FSGg1WUhhdmFlUjdQb25jSzMwcUlpWTg0ZHdBVFRNNGlzYSs2ZApTZmJOcy9GMGYvM2Ftekl3dEovOVNHWU5rWTZVR3JBcWFxVDBQMlJ3YXFuZGhCdXRzVlZhWjd6VURNMWozcFpXCmVySndwNEd4OVY2VWdicDV1L2VvbzlhYnJwNTJqWDFXYzFzSzVWY0NnWUJJTDEwK1IzTGZKc3ZPZ0dGYzMyTFUKNnc1WW15QUFQeG1Hb1phQ3ZUaFRBTDMwNys2V1hGZE9tVTI3RWFUdGNBbnVCeVAwYnBldStyQU53VW9sVEtMRApmVHo1ZXd3ZEkzSWpvMFMwUHNEL0RCTUVTOXlWaFNTekE1Vk12SVMxVXBxWWpsdjRNbWZsSlg3eHJIaFBPRmUxCmFFSzR1U0ZXeVRUblFYbDlGMnR1T1FLQmdHVFhCZHNjbmRoM21UbVI5aXRPcEw4ajFubXI1UW1sdVFwc0ZySTMKQ0Z1TU9KVHhzSXIvTkxvbTFtUWc4VEVlaXFLM0JRRGJoS1hid1lhVGI3OVZDaENPdmFEaEdQYW1pQ0JQeUhOQgp5WXRPT3I2WjNqRWdZV0k3OERmeUxHajBlYk1ONkV2MU5sMEtidEJGS0hPRGhaTE1OSlRtRnVyZVhsNFZtbFMyClZoS0pBb0dBWUtCNTRMYmFYRnc1S0xYWUdBMFNRQ3F0ck9hdWI1NzFhSVB5WW1XSE1FRndCN1ZmVVB5SWZUdG8KaWhDb0tMVDNRWENIMjlyRWxKWlJLZStiV3ZpcWJnMGx2MmM1QzBVTXZMU1RxTXhHNTlnREdwMXB3YUNQSnJuRQpOZzZMb0xTZDlzUGxCc1NkQysrUldtNlVMeW9pODRpRnNpQklJQmJpK0plazJzSmlCOWs9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2026-03-04T08:01:36Z"
    labels:
      app.kubernetes.io/name: argocd-secret
      app.kubernetes.io/part-of: argocd
    name: argocd-secret
    namespace: argocd
    resourceVersion: "1200"
    uid: 04ee2422-7a08-4bed-85ef-d293b435176c
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
