apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIM83eBwa71EEwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjAzMDQwNzUzMjJaFw0zNjAzMDEwNzU4MjJaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDJbLj+lCvyAU+KzPeVEPIMn1r8iiMsokE+KxalbPRNr0FxK3M592izb7D1
      cSQBeu9Dgak+cZzsUJ1uIjehBdZX6nJk6BPRN8+7uG0thtoK0qfGbyvB1DCV7b5U
      GwPA5ADPWzjyq0LXsTW1/MDqIm29tuWaz3tHITpvisgWKwi+6g7iPgQHua6iJIgI
      ccU6rhzKJlWztNS3rhg+kDhLvNbXvNXmhW39gjTgY3hLaKg/mkKbSvZfz+m5vo7X
      3+ep/zrpGjqmrBT/uVVjkarVE/eiOusnj/PD1CnkfjrfIohttp4B9kdnck/OlQO4
      gFai52TcWZkRhB/XZbr+WvIJtX3HAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTrCDjLFPzDWkAK2vVn37ypTdvZATAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCEQS9LuImS
      m7c3QfIEI6yUXyEkPGeCSrXwgpaolscLiuy8Nje4Eo1EUMRzHzPAqEqlRTHAfO30
      JpcBsYgc4X0YWiTJ/+jVzWiwuu/gFS8Fsx1fBKjAhdgyKQTUa6mB1L/8Ky3JLuvF
      Ek8eWAXK+lCmkNLnSj4vhmoYmGPdegaske8EP7kSJ/eKR8zcOSSM7N2UkTwyTXti
      q8tEKvHNeoHp7ZZTzvdg1NoqIWXAxyUOAU9ucP8wNWGso0FR1FgoAcepoRFiRMh+
      CPj2inzYPFbh3QxzUBehhNNi4OX1GAbvfTynNdfQqYXrOx9z3Tl1/KsZVpljc4uA
      hmZwl+pLZev3
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-04-17T12:58:55Z"
    name: kube-root-ca.crt
    namespace: database
    resourceVersion: "5567194"
    uid: 9d1522c7-498b-410f-ac0a-9a9c827e57d3
kind: List
metadata:
  resourceVersion: ""
