apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: ubuntu
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-03-10T02:50:06Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/name: postgresql
    name: data-postgres-postgresql-0
    namespace: axric
    resourceVersion: "724127"
    uid: d6e9f790-61c1-45db-bb97-7ea482341382
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-d6e9f790-61c1-45db-bb97-7ea482341382
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
