apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: axric-k8s-export
  namespace: argocd
spec:
  revisionHistoryLimit: 3
  project: default
  source:
    repoURL: https://github.com/box-plot/k8s-manifests.git
    targetRevision: main
    path: k8s/charts
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: axric
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
