apiVersion: apps/v1
kind: Deployment
metadata:
  name: axric-fe #name of deployment
  namespace: axric #namespace of deployment
spec:
  replicas: 2 #number of replicas (load balancing)
  selector:
    matchLabels:
      app: axric-fe #label selector for deployment
  template:
    metadata:
      labels:
        app: axric-fe #labels for pods
    spec:
      containers:
        - name: axric-fe #name of container
          image: jaron197/axric-fe:v1.0.3 #image of container
          imagePullPolicy: Always
          ports:
            - containerPort: 80



# Cluster axric 
# -Node Geust 192.xxx.xxx.1 (Chonburi)
#  namespace
#  - argo
#  - axric
#   - pods
#    - axric-fe-xxxx-xxxx (replica3)
#    - axric-fe-xxxx-xxxx (replica3)
#    - axric-fe-xxxx-xxxx (replica3)
#  - kube-system

#  -Node Geust 192.xxx.xxx.2 (Bangkok)
#  namespace
#  - argo
#  - axric
#   - pods
#    - axric-fe-xxxx-xxxx (replica3)
#    - axric-fe-xxxx-xxxx (replica3)
#    - axric-fe-xxxx-xxxx (replica3)
#  - kube-system

