apiVersion: v1
kind: Service
metadata:
  name: axric-fe
  namespace: axric 
spec:
  type: NodePort #service type
  selector:
    app: axric-fe #label selector for service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30432