apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: axric
data:
  default.conf: |
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
            proxy_pass http://axric-fe:80;  # your frontend service
        }
    }