{{- range $name, $cm := $.Values.configMaps.rekakim }}
{{- if (default true $cm.enabled) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $cm.namespace | default $.Values.apps.rekakimBackend.namespace }}
  labels:
    {{- include "k8s-export.labels" $ | nindent 4 }}
data:
  {{- toYaml $cm.data | nindent 2 }}
{{- end }}
{{- end }}

