{{- range $appName, $app := .Values.apps }}
{{- if and (default true $app.enabled) (ne $appName "threadlyBackend") (hasKey $app "image") (hasKey $app "name") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app.name }}
  namespace: {{ include "k8s-export.namespace" $ }}
  labels:
    {{- include "k8s-export.appLabels" (dict "name" $app.name "root" $) | nindent 4 }}
spec:
  replicas: {{ default 1 $app.replicaCount }}
  revisionHistoryLimit: {{ default 3 $app.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $app.name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  strategy:
    type: {{ $app.strategy | default "RollingUpdate" }}
    {{- if eq ($app.strategy | default "RollingUpdate") "RollingUpdate" }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "k8s-export.appLabels" (dict "name" $app.name "root" $) | nindent 8 }}
    spec:
      containers:
      - name: {{ $app.name }}
        image: {{ $app.image }}
        imagePullPolicy: {{ $app.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ $app.containerPort | default 8080 }}
        {{- if or $app.envFrom.configMaps $app.envFrom.secrets }}
        envFrom:
        {{- range $app.envFrom.configMaps }}
        - configMapRef:
            name: {{ . }}
        {{- end }}
        {{- range $app.envFrom.secrets }}
        - secretRef:
            name: {{ . }}
        {{- end }}
        {{- end }}
        {{- if $app.livenessProbe }}
        livenessProbe:
          {{ toYaml $app.livenessProbe | nindent 20 }}
        {{- end }}
        {{- if $app.readinessProbe }}
        readinessProbe:
          {{ toYaml $app.readinessProbe | nindent 20 }}
        {{- end }}
        {{- with $app.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
